### ISSUE TITLE
Consolidate PDF extracted text into one .txt file

### ISSUE THREAD

**Issue by GRCC-CODE-RAIDERS** [GRCC-CODE-RAIDERS/Enrollment-Analysis#1]
**Describe the solution you'd like**
We have a bunch of text from the enrollment report PDF files. Let's extract it and just put it into a single text file, maybe we can better work with the data this way.

**Comment by StevenWangler** [comment]
I'll work on this one

**Comment by StevenWangler** [comment]
This has been completed.
